module.exports = {
    gallery: [
        { image: '/img/Services/service-1.jpg', title: 'Apex Legends', category: 'Game', description: 'A description of our service...' },
        { image: '/img/Services/service-2.jpg', title: '33', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-3.jpg', title: '15', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-4.jpg', title: 'PC', category: 'Platform', description: 'A description of our service...' },
        { image: '/img/Services/service-5.jpg', title: '45', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-6.jpg', title: 'Overwatch', category: 'Game', description: 'A description of our service...' },
        { image: '/img/Services/service-7.jpg', title: '50', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-8.jpg', title: 'Playstation', category: 'Platform', description: 'A description of our service...' },
        { image: '/img/Services/service-9.jpg', title: '21', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-10.jpg', title: 'Rainbow Six Seige', category: 'Game', description: 'A description of our service...' },
        { image: '/img/Services/service-11.jpg', title: 'Overwatch', category: 'Game', description: 'A description of our service...' },
        { image: '/img/Services/service-12.jpg', title: '26', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-13.jpg', title: '25', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-14.jpg', title: '17', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-15.jpg', title: 'Call of Duty', category: 'Game', description: 'A description of our service...' },
        { image: '/img/Services/service-16.jpg', title: 'Xbox', category: 'Platform', description: 'A description of our service...' },
        { image: '/img/Services/service-17.jpg', title: 'PC', category: 'Platform', description: 'A description of our service...' },
        { image: '/img/Services/service-18.jpg', title: '19', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-19.jpg', title: '23', category: 'Age', description: 'A description of our service...' },
        { image: '/img/Services/service-20.jpg', title: 'CS:GO', category: 'Game', description: 'A description of our service...' },
    ],
    categories: ['All', 'Game', 'Age', 'Platform']
}